# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2995823159bf50aca5eb238fda5d69cd6079e2785dd5e0291ce5bd6fbfd3041a97858e96f10031d8137d4dde783ceb330e56a5849f70605c52ef9358097efa8

test:
  secret_key_base: 33cb6dc817cbccdd5289ab583ed4454cf1704536a16908e4b64e4858fa8e6861c7ec61c1e54ed2956ea907a94b5b211e755cfd900bcdc0e0021750837ef781c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
